### ISSUE TITLE
Handling Authorization

### ISSUE THREAD

**Issue by hugominas** [doquangtan/gofiber-socket.io#8]
@doquangtan thanks so much for the work you've put on the gofiber-socket.io I am a go newbie but have worked with socketio before.

I am trying to retrieve the handshake information to get Authorization token on the OnConnection as I am not able to pass down information from io.OnAuthorization where I validate and get the token claims to io.OnConnection.

is it possible to expose this to retrive the auth data? 

I have also tried building a client map, but  OnAuthorization has no socket.Id to match it OnConnection.

Thanks in advance for your help.

**Comment by hugominas** [comment]
I think I got it, you can access the Conn Query inside OnConnection, so I can just handle the token then to become available.

```
```

**Comment by doquangtan** [comment]
If token is validate you on  io.OnAuthorization return true to accept. If return false or nil it wil reject

**Comment by doquangtan** [comment]
client:
 setup auth here https://socket.io/docs/v4/client-options/#auth

server:
io.OnAuthorization(func(params map[string]string) bool {
	token, ok := params["Authorization"]
	if !ok {
		return false
	}
        //Validate your token here if wrong just return false
	return true
})

**Comment by hugominas** [comment]
@doquangtan Thanks for your reply, yes the authorization was not a problem the issue was getting the token data later in the process, but I could get the token later on io.OnConnection make it available to all routes socket.Conn.Query("token"), this is important when you have permissions for different routes after the initial auth is granted. Thank you
